---
name: Test Action

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Action
        uses: ./
        with:
          files: README.md src/*.py
          tag: "test_release"
      - name: Check output
        shell: bash
        run: |
          api="https://api.github.com/repos/zckv/action-update-release"
          read -r README_sum < <(sha256sum README.md | cut -d ' ' -f1)
          read -r action_sum < <(sha256sum src/action_update_release.py | cut -d ' ' -f1)
          README_sum="sha256:$README_sum"
          action_sum="sha256:$action_sum"
          readarray -t asset_sums < <(curl -sL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "$api/releases/286913097/assets" \
          | jq -r '.[] | .digest'
          )
          [[ " ${asset_sums[*]} " == *" $README_sum "* ]] ||echo "README.md was not uploaded correctly" && exit 1
          [[ " ${asset_sums[*]} " == *" $action_sum "* ]] ||echo "src/action_update_release.py was not uploaded correctly" && exit 1
